cacheFolder: .yarn/cache

enableScripts: false

immutablePatterns:
  - "**"

nodeLinker: node-modules

npmAlwaysAuth: false

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"
