cacheFolder: .yarn/cache

enableScripts: false

immutablePatterns:
  - "**"

nodeLinker: node-modules

npmAlwaysAuth: false

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  # Tell commitlint/load that its missing peers (@types/node, typescript)
  # do exist (hoisted at the workspace root) and should be treated as optional
  "@commitlint/load@*":
    peerDependencies:
      "@types/node": "*"
      typescript: ">=4"
    peerDependenciesMeta:
      "@types/node":
        optional: true
      typescript:
        optional: true

  # Tell commitlint/cli that it also "provides" those peers to its child commitlint/load
  "@commitlint/cli@*":
    peerDependencies:
      "@types/node": "*"
      typescript: ">=4"
    peerDependenciesMeta:
      "@types/node":
        optional: true
      typescript:
        optional: true
